### PR TITLE
fix: onContextChanged not running for named providers

### LINKED ISSUE #488: web-sdk: onContextChange not called for named provider
### Observed behavior
I am not sure to understand how do you change the context for a named provider?

Let's say I am doing something like this :
```javascript
await OpenFeature.setContext({targetingKey: 'foo'});
OpenFeature.setProvider('my-provider', provider);
const client = await OpenFeature.getClient('my-provider');
//...
await OpenFeature.setContext({targetingKey: 'bar'});
```

### Expected Behavior
I was expecting the function `onContextChange` of the provider to be called when changing the context.
But when looking at the code https://github.com/open-feature/js-sdk/blob/5725194393329cb65cf82a7a76c4ed2bd5d7bcf0/packages/client/src/open-feature.ts#L37-L41

 it seems that this function is called only for the default provider.

Is it something expected? Did I miss something to be sure that `onContextChange` is call on the provider.

### PR DESCRIPTION
**Pull request by lukas-reining**
## This PR

Fixes context propagation for the static-context-paradigm as found in #488.

### Related Issues

Fixes #488

### CODE REVIEW

**Review by thomaspoignant — APPROVED** [review]
Nice and simple 👍

**Comment by lukas-reining** [comment]
The onContextChanged is now called for all providers.
I am not sure if some requirement is still missing for the new spec @toddbaert @beeme1mr?

I think what we still have to do is check the numbering of all tests as we mostly used requirement names for the describe blocks, and the number shifted a bit.

File: packages/client/src/open-feature.ts [hunk 1]
```diff
@@ -37,7 +37,9 @@ export class OpenFeatureAPI extends OpenFeatureCommonAPI<Provider> implements Ma
   async setContext(context: EvaluationContext): Promise<void> {
     const oldContext = this._context;
     this._context = context;
-    await this._defaultProvider?.onContextChange?.(oldContext, context);
+
+    const allProviders = [this._defaultProvider, ...this._clientProviders.values()];
+    await Promise.all(allProviders.map((provider) => provider.onContextChange?.(oldContext, context)));
```
Comment (beeme1mr) [inline packages/client/src/open-feature.ts:42]: Promise.all would fail fast if any of the `onContextChange` methods threw. I think we should catch and log an error or use Promise.allSettled.

**Comment by beeme1mr** [comment]
I've created an issue to update the review and update test names to match the updated spec.

https://github.com/open-feature/js-sdk/issues/492

File: packages/client/src/open-feature.ts (hunk 1 above)
Comment (toddbaert) [reply packages/client/src/open-feature.ts:42]: I agree. One provider's error should not impact others. We may need to mention this in the spec.

Comment (lukas-reining) [reply packages/client/src/open-feature.ts:42]: Good point, will add it. That was actually my question in the issue.

Comment (lukas-reining) [reply packages/client/src/open-feature.ts]: @beeme1mr @toddbaert Fixed it now

**Review by beeme1mr — APPROVED** [review]

**Review by toddbaert — APPROVED** [review]
lgtm

**Comment by toddbaert** [comment]
@lukas-reining I'm not sure this is a feat, I think it was more of a fix, but I'm not 100% sure it matters TBH, we are still sub 1.0/experimental.

Though TBH, we should probably publish our first non-experimental soon.
