### PR TITLE
fix: only shutdown providers that are not attached to any client

### LINKED ISSUE #443: [BUG] Bound providers are shutdown while attached to clients
### Observed behavior

Providers that are bound to several named clients are closed if another provider is set for one of these clients.
Spec Issue: https://github.com/open-feature/spec/issues/192

### Expected Behavior

_No response_

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by lukas-reining**
## This PR

Providers that are bound to several named clients are closed if another provider is set for one of these clients.
This PR only closes providers if they are not used by any client.

### Related Issues

Fixes #443 

### How to test

Added tests for server and client.

### CODE REVIEW

File: packages/shared/src/open-feature.ts [hunk 1]
```diff
@@ -129,10 +129,11 @@ export abstract class OpenFeatureCommonAPI<P extends CommonProvider = CommonProv
 
     this.transferListeners(oldProvider, provider, clientName, clientEmitter);
 
-    // Do not close the default provider if a named client used the default provider
-    if (!clientName || (clientName && oldProvider !== this._defaultProvider)) {
+    // Do not close a provider, that is bound to any client
```
Comment (beeme1mr) [inline packages/shared/src/open-feature.ts:132]:
```suggestion
    // Do not close a provider that is bound to any client
```

**Review by beeme1mr — APPROVED** [review]
Nice change

**Comment by beeme1mr** [comment]
@toddbaert are you waiting for the spec change to be merged? If so, could you link that PR here?

**Comment by lukas-reining** [comment]
No personally I would be open to merge it.
I just can not😅

**Comment by toddbaert** [comment]
> @toddbaert are you waiting for the spec change to be merged? If so, could you link that PR here?

Ya, I'm waiting for https://github.com/open-feature/spec/pull/193 just to avoid any thrashing.

**Review by toddbaert — APPROVED** [review]
This LGTM. I will wait to merge once https://github.com/open-feature/spec/pull/193 is merged.
