### PR TITLE
fix: run error hook when provider returns reason error or error code

### LINKED ISSUE #925: [BUG] Error hooks only run if the provider throws
### Observed behavior

The error hook only runs if the provider throws an exception. However, it's possible for a provider to return an error code in the `ResolutionDetails`.

### Expected Behavior

The error hook runs if the `ResolutionDetails` contains an `errorCode`

### Steps to reproduce

1. Register a provider that returns a `ResolutionDetails` object with an `errorCode`
2. Register a hook that relies on the error hook
3. Evaluate a flag

### PR DESCRIPTION
**Pull request by beeme1mr**
## This PR

- runs error hook when provider returns reason error or error code

### Related Issues

Fixes #925

### Notes

Based on a conversation in Slack: https://cloud-native.slack.com/archives/C06E4DE6S07/p1714581197391509

### CODE REVIEW

File: packages/client/src/client/open-feature-client.ts [hunk 1]
```diff
@@ -225,6 +226,16 @@ export class OpenFeatureClient implements Client {
...
       };
 
+      if (evaluationDetails.errorCode || evaluationDetails.reason === StandardResolutionReasons.ERROR) {
+        const errorCode = evaluationDetails.errorCode || ErrorCode.GENERAL;
+        this.errorHooks(allHooksReversed, hookContext, instantiateErrorByKey(errorCode), options);
+        return {
+          ...evaluationDetails,
+          errorCode,
+          reason: StandardResolutionReasons.ERROR,
+        };
```
Comment (beeme1mr) [inline packages/client/src/client/open-feature-client.ts:236]: I'm also setting the reason to error. This will override the reason set by the provider. Does this make sense or should we return the reason defined in the evaluation details?

File: packages/client/test/hooks.spec.ts [hunk 2]
```diff
@@ -206,6 +208,48 @@ describe('Hooks', () => {
...
+        const mockErrorHook = jest.fn();
+
+        const details = client.getBooleanDetails(FLAG_KEY, false, {
+          hooks: [{ error: mockErrorHook }],
+        });
+
+        expect(mockErrorHook).toHaveBeenCalled();
+        expect(details).toEqual(
+          expect.objectContaining({
+            errorCode: ErrorCode.GENERAL,
```
Comment (beeme1mr) [inline packages/client/test/hooks.spec.ts:248]: Error code is automatically set to `GENERAL` if the provider didn't explicitly define a code.

File: packages/client/src/client/open-feature-client.ts (hunk 1 above)
Comment (lukas-reining) [reply packages/client/src/client/open-feature-client.ts:236]: I think error is good here!

**Review by lukas-reining — APPROVED** [review]
Nice, I like the change!

File: packages/shared/src/errors/index.ts [hunk 3]
```diff
@@ -1,9 +1,45 @@
...
+import { InvalidContextError } from './invalid-context-error';
+import { OpenFeatureError } from './open-feature-error-abstract';
+import { ParseError } from './parse-error';
+import { ProviderFatalError } from './provider-fatal-error';
+import { ProviderNotReadyError } from './provider-not-ready-error';
+import { TargetingKeyMissingError } from './targeting-key-missing-error';
+import { TypeMismatchError } from './type-mismatch-error';
+
+const instantiateErrorByKey = (key: ErrorCode, message?: string): OpenFeatureError => {
+  switch (key) {
```
Comment (beeme1mr) [inline packages/shared/src/errors/index.ts:14]:
```suggestion
const instantiateErrorByErrorCode = (errorCode: ErrorCode, message?: string): OpenFeatureError => {
  switch (errorCode) {
```

File: packages/server/src/client/open-feature-client.ts [hunk 4]
```diff
@@ -278,6 +279,16 @@ export class OpenFeatureClient implements Client, ManageContext<OpenFeatureClien
         flagKey,
       };
 
+      if (evaluationDetails.errorCode || evaluationDetails.reason === StandardResolutionReasons.ERROR) {
+        const errorCode = evaluationDetails.errorCode || ErrorCode.GENERAL;
+        await this.errorHooks(allHooksReversed, hookContext, instantiateErrorByErrorCode(errorCode), options);
+        return {
+          ...evaluationDetails,
```
Comment (toddbaert) [inline packages/server/src/client/open-feature-client.ts:286]: Should we add our own `errorMessage` if one wasn't supplied by the provider?

I suspect in most cases they would populate one, and if we added one it might not be very informative... we could add something like `"provider returned error code"`... Leaning towards no, but wanted to mention it.

File: packages/server/src/client/open-feature-client.ts [hunk 5]
```diff
@@ -278,6 +279,16 @@ export class OpenFeatureClient implements Client, ManageContext<OpenFeatureClien
         flagKey,
       };
 
+      if (evaluationDetails.errorCode || evaluationDetails.reason === StandardResolutionReasons.ERROR) {
```
Comment (toddbaert) [inline packages/server/src/client/open-feature-client.ts:282]: This is the only thing that gives me pause.

I wonder if it might be better to predicate this failure _only_ on the `errorCode` being present. Having a very concise rule is arguably better than one with an "or".

ie: `if the provider sets an error code, error hooks must run and the default must be returned` is more cut and dry than `if the provider sets an error code or set's the reason to "ERROR", error hooks must run and the default must be returned`.

Comment (maxveldink) [reply packages/server/src/client/open-feature-client.ts:282]: Yeah, I agree that the few places we check for errors in the Ruby code, it's on the presence of _anything_ in `error_code`. `reason` seems like a much more ambiguous field that some providers might not fill out on error, so I think ignoring it for error flows makes sense to me.

File: packages/server/src/client/open-feature-client.ts (hunk 4 above)
Comment (beeme1mr) [reply packages/server/src/client/open-feature-client.ts:286]: I don't think that provides any additional information that would be useful. If the provider sets an error message, it will be retained, but setting a default message would basically rephrase the same information that's already available.

File: packages/server/src/client/open-feature-client.ts (hunk 5 above)
Comment (beeme1mr) [reply packages/server/src/client/open-feature-client.ts]: Okay, thanks for the feedback. I've updated the PR with this change.

File: packages/client/src/client/open-feature-client.ts [hunk 6]
```diff
@@ -225,6 +226,19 @@ export class OpenFeatureClient implements Client {
         flagKey,
       };
 
+      if (evaluationDetails.errorCode) {
+        this.errorHooks(
```
Comment (federicobond) [inline packages/client/src/client/open-feature-client.ts:230]: In the Python SDK we construct and raise an appropriate exception here to avoid duplicating the error handling code from the catch clause. Would it make sense to do something similar?

**Review by toddbaert — APPROVED** [review]

File: packages/client/src/client/open-feature-client.ts (hunk 6 above)
Comment (toddbaert) [reply packages/client/src/client/open-feature-client.ts:230]: I did a little investigation into this and it looks like in node, stack traces are captured in the error constructor. So calling `new Error()` captures the stack trace and results in significant performance penalty ([reference](https://nodejs.org/api/errors.html#class-error)). This is news to me, I actually thought it happened with the throw (something c# does).

Provider authors returning an error the way we do in this PR has some benefits, in that if it's a error condition that's well understood and doesn't benefit from a stack trace and a proper exception, they could return an error and avoid the performance hit. If we instantiate our own exception anyway, we've negated that performance improvement.

We _could_ instantiate and throw a non-error, but that could be confusing and lead to unexpected bugs.

Comment (federicobond) [reply packages/client/src/client/open-feature-client.ts:230]: But that's what `instantiateErrorByErrorCode` does a couple of lines below, or am I missing something? If I understand you correctly, the performance cost of instantiating this error would be paid in both cases.

Comment (toddbaert) [reply packages/client/src/client/open-feature-client.ts:230]: Ya, I was being very unclear.

This PR _does_ carry the performance penalty I mentioned already. The way to avoid that would be to construct something shaped like an error that doesn't capture the stack trace, that's what I meant by:

> We could instantiate and throw a non-error, but that could be confusing and lead to unexpected bugs.

Irrespective of that, the flow could be improved by doing what you suggest I think; sorry, I got carried away by my own research how the stack trace is built and got away from your original point.

Comment (beeme1mr) [reply packages/client/src/client/open-feature-client.ts:230]: I've made this change. Thanks for the suggestion.

**Review by toddbaert — APPROVED** [review]

**Comment by Kavindu-Dodan** [comment]
@toddbaert @beeme1mr 

In Go, there's no concept of throwing, so we rely on error details [^1] already

I created a follow-up for Java SDK [^2]

[^1]: - https://github.com/open-feature/go-sdk/blob/v1.11.0/openfeature/client.go#L747-L748
[^2]: - https://github.com/open-feature/java-sdk/issues/928
